### PR TITLE
feat: add debug-mode around all network requests

### PR DESCRIPTION
**Pull request by Integralist**
There was a bug recently which we were only able to identify and fix, by dumping a related HTTP request/response.

We have `--debug-mode` but currently it only passes that information to go-fastly which dumps the req/resp.

This PR adds the same logic as found in go-fastly and ensures all network requests are wrapped in conditional branches checking for debug mode being enabled.

### CODE REVIEW

**Review by kailan — APPROVED** [review]
This is so helpful – thank you!

**Comment by jsocol** [comment]
We also got a failure in `pkg/config/TestUseStatic` reading [`config-legacy.toml`](https://github.com/fastly/cli/blob/main/pkg/config/config_test.go#L208) which hasn't been touched in 2 years. Some kind of change to the MacOS runners recently?

**Comment by kpfleming** [comment]
This was the `tomlq` change; I'll update this branch and the tests should pass.

**Comment by kpfleming** [comment]
Tests are now passing, I'll merge this.

**Pull request merged**
