### PR TITLE
logging: adds Cloudfiles logging endpoint support

### PR DESCRIPTION
**Pull request by mccurdyc**
## Relevant (Referenced) Link(s)

* [Fastly API Docs](https://docs.fastly.com/api/logging#api-section-logging_cloudfiles)
* [fastly/go-fastly](https://github.com/fastly/go-fastly/blob/c2c2c62210800daab641161412fbe210004aac0a/fastly/cloudfiles.go)

## Validation

```
$ make test
```

```
git clone git@github.com:mccurdyc/cli.git /tmp/cli && \
(
    cd /tmp/cli && \
    git checkout mccurdyc/logging-cloudfiles && \
    make test && \
    rm -rf /tmp/cli \
)
```

### CODE REVIEW

**Comment by pteichman** [comment]
Conflict fix is at https://github.com/fastly/cli/commit/10a950824bde6c9f766a1acb266288b91ab09e81

**Comment by mccurdyc** [comment]
Force-pushed Peter's commit.

**Comment by mccurdyc** [comment]
Force-pushed rebasing master.

**Comment by mccurdyc** [comment]
Force-pushed rebasing master.

**Comment by mccurdyc** [comment]
Force-pushed squashed commit for fixing failed CI check.

**Pull request merged**
