### PR TITLE
Add support for interacting with the New Relic OTLP logging endpoint

### PR DESCRIPTION
**Pull request by kellymclaughlin**

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Will mark this ready for review after the next `go-fastly` version is tagged and I update the dependency to use that tag.

**Comment by Integralist** [comment]
@kellymclaughlin https://github.com/fastly/go-fastly/releases/tag/v8.5.8

**Comment by kellymclaughlin** [comment]
Looks like this PR is getting the same failure as [this](https://github.com/fastly/cli/pull/992) PR that just bumps the `go-fastly` version.

**Comment by Integralist** [comment]
@kellymclaughlin looks like this PR has gone stale.

**Comment by kellymclaughlin** [comment]
@Integralist Thanks for the heads up. I've rebased the branch and it looks like all the tests are happy now.

**Review by Integralist — APPROVED** [review]

**Pull request merged**
