### PR TITLE
Update Go-Fastly dependency to v3.0.0

### PR DESCRIPTION
**Pull request by Integralist**
Bump the Go-Fastly dependency from 2.x.x to the latest 3.0.0 release.

### CODE REVIEW

**Review by phamann — APPROVED** [review]
👍🏻 LGTM

**Review by triblondon — APPROVED** [review]

**Review by christophermancini — APPROVED** [review]
Looks good to me, though I don't know the code that well yet.

**Comment by Integralist** [comment]
Thanks everyone. You probably all did this already but I should have suggested y'all review the [individual commits](https://github.com/fastly/cli/pull/193/commits), as the diff tab/view will be 99% copy/paste fix of the import path 😬

**Comment by Integralist** [comment]
Just to confirm for anyone unaware of the internal discussion:

> I intend to merge this PR now it's approved but I won't '_cut a release_' until we have https://github.com/fastly/cli/pull/192 updated to pull this PRs changes and itself be reviewed/approved/merged. Then I'll cut a new `v0.23.0` minor release.

**Pull request merged**
